### ISSUE TITLE
Error response from daemon: manifest for cimg/base:latest not found

### ISSUE THREAD

**Issue by judahtanthony** [CircleCI-Public/sumologic-orb#10]
### Orb version
1.0.0

### What happened
So from the looks of it the version of the circleci/sumologic@1.0.0 at https://circleci.com/orbs/registry/orb/circleci/sumologic#executors-default
has an executor defined as
```yml
description: >
  Default reporting environment for Sumologic. This is a small Ubuntu based
  Docker image with a low resource class. Designed to load fast and use few
  credits.
docker:
  - image: cimg/base
resource_class: small
```
This is problematic, as the default tag if not defined is latest which is not defined for the cimg/base image; however, your master branch, https://github.com/CircleCI-Public/sumologic-orb/blob/master/src/executors/default.yml, defines the executor like:
```yml
description: >
  Default reporting environment for Sumologic. This is a small Ubuntu based Docker image with a low resource class. Designed to load fast and use few credits.
parameters:
  image:
    type: string
    default: "cimg/base"
    description: Docker image name
  tag:
    type: string
    default: "stable"
    description: Docker image tag

docker:
  - image: <<parameters.image>>:<<parameters.tag>>

resource_class: small
```
which would be great (defining the tag as stable which DOES exist), if only that is what the orb registry had.  Can you update the orb registry?  Perhaps bump the version.

### Expected behavior
There shouldn't be a docker hub error ;)
